# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/chatgpt-telegram-bot:latest

jobs:
  push_to_registries:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
