name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT}}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/papa31/chatgpt-telegram-bot:latest
        docker run -d -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} ghcr.io/papa31/chatgpt-telegram-bot:latest
        docker push ghcr.io/papa31/chatgpt-telegram-bot:latest